---
- name: Install Apache on the Agent Node
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes
  
  tasks:
    - name: Install PostgreSQL repository (Amazon Linux 2)
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: Install PostgreSQL server
      yum:
        name: postgresql13-server
        state: present

    - name: Initialize PostgreSQL database
      command: /usr/pgsql-13/bin/postgresql-13-setup initdb
      when: ansible_facts['distribution'] == 'Amazon'

    - name: Enable and start PostgreSQL service
      service:
        name: postgresql-13
        state: started
        enabled: yes

    - name: Verify PostgreSQL service status
      command: systemctl status postgresql-13
      register: result
      failed_when: "'active (running)' not in result.stdout"
      changed_when: false

